---
- name: Common provision
  hosts: all
  become: true
  gather_facts: false
  roles:
    - apt_sources
    - chrony
    - ceph_common

- name: Ceph cluster provision
  hosts: [mds, mon]
  become: true
  gather_facts: false
  roles:
    - ceph

- name: Ceph client provision
  hosts: [cli]
  become: true
  gather_facts: false
  roles:
    - ceph_client
...
