---
- name: Install chrony
  ansible.builtin.apt:
    name: chrony
    update_cache: true
    cache_valid_time: 3600
    state: present
  retries: 10
  delay: 10
  tags: chrony

- name: Ensure chronyd is running
  ansible.builtin.systemd:
    name: chronyd
    enabled: true
    state: started
  tags: chrony
...
